spring:
  application:
    name: zuul-gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
zuul:
  routes:
      batch:
        path: /batch/**
        serviceId: batch-feign
      basic:
        path: /basic/**
        serviceId: basic-service
